# Generated by Django 5.0.4 on 2024-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kairat", "0002_player_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="player",
            name="country",
        ),
        migrations.RemoveField(
            model_name="player",
            name="position",
        ),
        migrations.RemoveField(
            model_name="player",
            name="surname",
        ),
        migrations.AddField(
            model_name="player",
            name="birthday",
            field=models.DateField(null=True, verbose_name="День рождения"),
        ),
        migrations.AddField(
            model_name="player",
            name="city",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Город"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="course",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Курс"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="ent_score",
            field=models.IntegerField(default=0, verbose_name="Баллы ЕНТ"),
        ),
        migrations.AddField(
            model_name="player",
            name="hobby",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Хобби"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="school",
            field=models.CharField(default=1, max_length=100, verbose_name="Школа"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="specialty",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Специальность"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.CharField(max_length=150, verbose_name="Возраст"),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
    ]
